POST http://localhost:3000/api/addcontact
Content-Type: application/json

{
    "nama_lengkap":"Product 6", "email": "email", "nohp": "082333222111"

}
###
DELETE http://localhost:3000/api/deletecontact
Content-Type: application/json

{
    "id": 12

}