POST http://localhost:3000/api/addcontactdetail
Content-Type: application/json

{
    "id_biodata": 1, "id_sosial_media": 10, "status": true

}
###
DELETE http://localhost:3000/api/deletecontactdetail
Content-Type: application/json

{
    "id": 12

}

###
PATCH http://localhost:3000/api/updatecontactdetail/24
Content-Type: application/json

{
    "status": 0
}